language: node_js
node_js:
  - "8"
  - "lts/*"
  - "node"

cache:
  directories:
    - "node_modules"

## Spin up glitlab instance and sleep for 60 seconds
before_script:
  ## Spin up container
  - cd test/docker/
  - docker-compose -f docker-compose.test.yml up -d

  ## Get the docker env variables
  - echo $(docker exec -it gitlab bash -lc 'echo "$GITLAB_URL"')

  - export PERSONAL_ACCESS_TOKEN=$(docker exec -it gitlab bash -lc 'echo "$GITLAB_URL"')
  - export GITLAB_URL=$(docker exec -it gitlab bash -lc 'echo "$GITLAB_URL"')

  ## Sleep before performing commands on container
  - sleep 30

  - env
## run tests
script:
  - npm run test

after_script:
  - docker-compose -f docker-compose.test.yml down

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: build
      script: npm run build
