language: node_js

stages:
  - lint
  - build
  - test
  - coverage
  - release

notifications:
  email: false

cache:
  directories:
    - coverage
    - dist

jobs:
  include:
    - stage: lint
      node_js: node
      script:
        - npm run lint
        - prettier --check './*.json' './*.yml' './*.js' # Semantic release modified the md files that are not styled correctly.

    - &build
      stage: build
      node_js: lts/*
      script:
        - npm run build

    - <<: *build
      node_js: node

    - &test-unit
      stage: test
      node_js: lts/*
      name: 'Unit Tests  Latest LTS'
      script:
        - npm run test:unit -- --collectCoverage

    - &test-integration
      stage: test
      node_js: lts/*
      name: 'Integration Tests Latest LTS'
      before_script:
        ## Spin up container
        - cd test/docker/
        - docker-compose -f docker-compose.test.yml up -d
        - sleep 260
        - export PERSONAL_ACCESS_TOKEN=$(docker exec -it gitlab bash -lc 'printf "%q" "${PERSONAL_ACCESS_TOKEN}"')
        - export GITLAB_URL=$(docker exec -it gitlab bash -lc 'printf "%q" "${GITLAB_URL}"')
        - echo $GITLAB_URL
        - echo $PERSONAL_ACCESS_TOKEN
      script:
        - npm run test:integration -- --collectCoverage

    - <<: *test-unit
      name: 'Unit Tests Latest'
      node_js: node
      script:
        - npm run test:unit

    - <<: *test-integration
      name: 'Integration Tests Latest'
      node_js: node
      script:
        - npm run test:integration

    - stage: coverage
      node_js: node
      script:
        - npm run coverage

    - stage: release
      node_js: node
      script:
        - npm run release
