language: node_js
node_js:
  - "8"
  - "lts/*"
  - "node"

cache:
  directories:
    - "node_modules"

## Spin up glitlab instance and sleep for 60 seconds
before_script:
  ## Spin up container
  - cd test/docker/
  - docker-compose -f docker-compose.test.yml up -d
  - cd .
  
  - docker exec -i gitlab echo $PERSONAL_ACCESS_TOKEN
  ## Get the docker env variables
  - PERSONAL_ACCESS_TOKEN=$(docker exec -i gitlab echo $PERSONAL_ACCESS_TOKEN)
  - GITLAB_URL=$(docker exec -i gitlab echo $GITLAB_URL)
  - echo $PERSONAL_ACCESS_TOKEN
  - echo $GITLAB_URL
  ## Sleep before performing commands on container
  - sleep 30

## run tests
script:
  - npm run test

after_script:
  - docker-compose -f docker-compose.test.yml down

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: build
      script: npm run build
