language: node_js
node_js:
  - "8"
  - "lts/*"
  - "node"

cache:
  directories:
    - "node_modules"

## Spin up glitlab instance and sleep for 60 seconds
before_script:
  ## Spin up container
  - docker-compose -f docker-compose.test.yml up

  ## Get the docker env variables
  - export PERSONAL_ACCESS_TOKEN=$(docker exec -i gitlab echo PERSONAL_ACCESS_TOKEN)
  - export GITLAB_URL=$(docker exec -i gitlab echo PERSONAL_ACCESS_TOKEN)

  ## Sleep before performing commands on container
  - sleep 10000

## run tests
script:
  - npm run test:infrastructure
  - npm run test:bundles

after_script:
  - docker-compose -f docker-compose.test.yml down

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: build
      script: npm run build
    #   script: npm run test:services