language: node_js
node_js:
  - "8"
  - "lts/*"
  - "node"

cache:
  directories:
    - "node_modules"

## Spin up glitlab instance and sleep for 60 seconds
before_script:
  ## Spin up container
  - cd test/docker/
  - docker-compose -f docker-compose.test.yml up -d

  ## Sleep before performing commands on container
  - sleep 240

  ## Get the docker env variables
  - export TESTS2=$(docker exec -it gitlab bash -lc 'printenv TEST')
  - export TESTS=$(docker exec -it gitlab bash -lc 'printenv EXTERNAL_PORT')
  - export PERSONAL_ACCESS_TOKEN=$(docker exec -it gitlab bash -lc 'printenv PERSONAL_ACCESS_TOKEN')
  - export GITLAB_URL=$(docker exec -it gitlab bash -lc 'printenv GITLAB_URL')

## run tests
script:
  - npm run test

after_script:
  - docker-compose -f docker-compose.test.yml down

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: build
      script: npm run build
