language: node_js

stages:
  - lint and build
  - test
  - release

cache:
  directories:
    - node_modules # NPM packages
    - ~/.npm

notifications:
  email: false

jobs:
  include:
    - stage: lint and build
      node_js: node
      script: npm run lint
      script: npm run build

    - &test
      stage: test
      before_script:
        ## Spin up container
        - cd test/docker/
        - docker-compose -f docker-compose.test.yml up -d

        ## Sleep before performing commands on container
        - sleep 240

        - export PERSONAL_ACCESS_TOKEN=$(docker exec -it gitlab bash -lc 'printf "%q" "${PERSONAL_ACCESS_TOKEN}"')
        - export GITLAB_URL=$(docker exec -it gitlab bash -lc 'printf "%q" "${GITLAB_URL}"')
      script: nvm install 8 && npm run test
      script: nvm install lts && npm run test
      script: nvm install 9 && npm run test
      script: nvm install node && npm run test

    - stage: release
      node_js: node
      script:
        - npm run semantic-release