language: node_js
node_js:
  - "8"
  - "lts/*"
  - "node"

cache:
  directories:
    - "node_modules"

## Spin up glitlab instance and sleep for 60 seconds
before_script:
  - docker-compose -f docker-compose.test.yml up
  ## Get the docker env variables
  - SET PERSONAL_ACCESS_TOKEN =
  - SET GITLAB_URL 
  - sleep 60

## run tests
script:
  - npm run test:infrastructure
  - npm run test:bundles

jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: build
      script: npm run build
    #   script: npm run test:services