stages:
  - prepare cache
  - lint
  - build
  - setup test docker
  - test

cache:
  directories:
  - node_modules # NPM packages

env:
  - PERSONAL_ACCESS_TOKEN
  - GITLAB_URL

jobs:
  include:
    - stage: prepare cache
      language: node_js
      node_js: node
      script: true

    - stage: lint
      language: node_js
      node_js: node
      script: npm run lint

    - stage: build
      language: node_js
      node_js: node
      script: npm run build

    - stage: setup test docker
      script:
         ## Spin up container
        - cd test/docker/
        - docker-compose -f docker-compose.test.yml up -d

        ## Sleep before performing commands on container
        - sleep 240

        ## Get the docker env variables
        - "$PERSONAL_ACCESS_TOKEN"=$(docker exec -it gitlab bash -lc 'printf "%q" "${PERSONAL_ACCESS_TOKEN}"')
        - "$GITLAB_URL"=$(docker exec -it gitlab bash -lc 'printf "%q" "${GITLAB_URL}"')

    - stage: test
      language: node_js
      node_js: 8
      script: npm run test

    - stage: test
      language: node_js
      node_js: lts/*

      script: npm run test

    - stage: test
      language: node_js
      node_js: 9
      script: npm run test

    - stage: test
      language: node_js
      node_js: node
      script: npm run test
