version: '3'
services:
  gitlab:
    image: gitlab/gitlab-ce
    container_name: gitlab
    entrypoint:
      - ./docker-entrypoint.sh
    environment:
      - GITLAB_URL='http://localhost:8080'
      - PERSONAL_ACCESS_TOKEN='token'
    ports: 
      - 8080:80
      - 8443:443